name: Visual Regression

on:
  push:
    branches:
      - main
      - master
    paths:
      - "apps/storybook-hub/**"
      - "packages/**"
      - "tests/storybook-visual.spec.ts"
      - "playwright.visual.config.ts"
      - ".github/workflows/visual-regression.yml"
  pull_request:
    paths:
      - "apps/storybook-hub/**"
      - "packages/**"
      - "tests/storybook-visual.spec.ts"
      - "playwright.visual.config.ts"
      - ".github/workflows/visual-regression.yml"
  workflow_dispatch:

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instala dependências
        run: npm ci

      - name: Instala navegadores do Playwright
        run: npx playwright install --with-deps chromium

      - name: Build do Storybook Hub
        run: npm run build --workspace @adsmagic/storybook-hub

      - name: Sobe servidor do Storybook
        run: |
          npx --yes http-server apps/storybook-hub/storybook-static -p 6006 --silent &
          npx --yes wait-on http://127.0.0.1:6006

      - name: Executa testes visuais
        run: npm run test:visual

      - name: Publica screenshots de diferenças (falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-diffs
          path: test-results/visual/
          if-no-files-found: ignore

      - name: Publica relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-report
          path: playwright-report/visual/
          if-no-files-found: ignore

      - name: Comentário no PR (falhas)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Visual Regression Failed**\n\nForam detectadas mudanças visuais nos testes. Verifique os artefatos desta execução para ver as diferenças.\n\n📎 [Download dos diffs visuais](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            })